project:
  type: website
  output-dir: docs

website:
  title: "Alina's health data science blog"
  page-navigation: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
sidebar:
  style: "docked"
  contents:
    - href: index.qmd
      text: Home
    - section: Posts
      contents:
        - posts/welcome/index.qmd
        - posts/post-with-code/index.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

editor: visual
